# Generated by Django 4.2.dev20220912115206 on 2023-11-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter_media', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
    ]
